@baseUrl = http://127.0.0.1:4000/api/v1

### list active containers
GET {{baseUrl}}/containers
Accept: application/json

### list all containers
GET {{baseUrl}}/containers?all=true
Accept: application/json


### delete container
DELETE {{baseUrl}}/containers/test-container

