@baseUrl = http://127.0.0.1:4000/api/v1

### list active containers
GET {{baseUrl}}/containers
Accept: application/json

### list all containers
GET {{baseUrl}}/containers?all=true
Accept: application/json

### inspect container
GET {{baseUrl}}/containers/9
Accept: application/json

### create container
POST {{baseUrl}}/containers
Content-Type: application/json

{
  "container": {
    "name": "test-container",
    "image_name": "recipes-rs",
    "host_port": "8080",
    "container_port": "8080/tcp",
    "proxy_port": "7080",
    "env": ["DATABASE_URL=postgres://postgres:postgres@hivex-postgres-1/postgres"]
  }
}

### delete container
DELETE {{baseUrl}}/containers/2

### force delete container
DELETE {{baseUrl}}/containers/8?force=true
