@baseUrl = http://127.0.0.1:4000/api/v1

### list users
GET {{baseUrl}}/services
Accept: application/json


### create user
POST {{baseUrl}}/services
Content-Type: application/json

{
  "service": {
    "name": "ja",
    "user_id": 1
  }
}

